name: Update README stats

on:
  schedule:
    - cron: "0 6 * * *" # todo dia 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate stats card
        run: |
          curl -L "https://github-readme-stats.vercel.app/api?username=andymarksss&show_icons=true&theme=github_dark&include_all_commits=true&hide_border=true&border_radius=6" \
          -o stats.svg

      - name: Generate langs card
        run: |
          curl -L "https://github-readme-stats.vercel.app/api/top-langs/?username=andymarksss&layout=compact&langs_count=8&theme=github_dark&hide_border=true&border_radius=6" \
          -o langs.svg

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add stats.svg langs.svg
          git commit -m "chore: update readme stats" || exit 0
          git push
